version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: trading-postgres
    restart: always
    environment:
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: trading_bot
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
